[theme]
primaryColor = "#E74C3C"  # A bold red for primary buttons
backgroundColor = "#F9F9F9"  # A light grey for a softer background
secondaryBackgroundColor = "#FFFFFF"  # Keep white for clean sections
textColor = "#34495E"  # A darker navy blue for better readability
font = "sans serif"  # Change font for a modern look
